stages:
  - build

default:
  services:
    - docker:dind
  before_script:
    - export CI_REGISTRY_IMAGE="$REGISTRY_HOST/$CI_PROJECT_NAME"
    - echo -n $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY_HOST || true


build IPK:
  image: golang:bullseye
  stage: build
  script:
    - curl -s https://git.yoctoproject.org/opkg-utils/plain/opkg-build >/usr/local/bin/opkg-build
    - chmod +x /usr/local/bin/opkg-build
    - apt-get update && apt-get install -y upx-ucl
    - make kerlink
  artifacts:
    paths:
      -  build/package/kerlink/dps-client_*_klkgw.ipk
